from __future__ import annotations

import argparse
import asyncio
import shutil
import subprocess
import sys
import time

from replaycore import ReplayEngine, ReplayStorage
from replaycore.models import Scenario, new_id


def cmd_seed() -> None:
    storage = ReplayStorage()
    if storage.list_scenarios():
        print('seed already present')
        return
    for idx in range(3):
        storage.create_scenario(
            Scenario(
                id=new_id('scn'),
                name=f'Seeded Scenario {idx+1}',
                description='Autogenerated seed scenario for demo',
                seed=10 + idx,
                target_url='http://127.0.0.1:9000/webhook',
                chaos_profile={'duplicates': idx * 0.2, 'out_of_order_window': idx, 'retry_storm': idx},
                expected_invariants={'charges_exactly_once': True},
            )
        )
    print('seeded scenarios')


async def _run_once(run_id: str | None = None) -> None:
    storage = ReplayStorage()
    scenarios = storage.list_scenarios()
    if not scenarios:
        cmd_seed()
        scenarios = storage.list_scenarios()
    scenario = scenarios[0]
    engine = ReplayEngine(storage)
    run = await engine.execute_run(scenario, seed=scenario.seed)
    print(f'completed run {run.id}')
    if run_id:
        print(f'replay requested {run_id}; deterministic seeds ensure reproducibility')


def cmd_replay(run_id: str | None) -> None:
    asyncio.run(_run_once(run_id))


def cmd_demo() -> None:
    cmd_seed()
    if not shutil.which('uvicorn'):
        print('uvicorn not installed; running deterministic offline demo mode')
        asyncio.run(_run_once())
        print('Install uvicorn+fastapi to enable live API/merchant services during demo.')
        return

    merchant = subprocess.Popen([sys.executable, '-m', 'uvicorn', 'apps.merchant.app.main:app', '--host', '127.0.0.1', '--port', '9000'])
    api = subprocess.Popen([sys.executable, '-m', 'uvicorn', 'apps.api.app.main:app', '--host', '127.0.0.1', '--port', '8000'])
    try:
        time.sleep(3)
        asyncio.run(_run_once())
        print('Demo is live at: API http://127.0.0.1:8000 | merchant http://127.0.0.1:9000')
        print('Run dashboard with: cd apps/dashboard && npm run dev')
    finally:
        api.terminate()
        merchant.terminate()


def main() -> None:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest='command', required=True)
    sub.add_parser('seed')
    demo_parser = sub.add_parser('demo')
    demo_parser.set_defaults(command='demo')
    replay = sub.add_parser('replay')
    replay.add_argument('run_id', nargs='?')
    args = parser.parse_args()

    if args.command == 'seed':
        cmd_seed()
    elif args.command == 'demo':
        cmd_demo()
    elif args.command == 'replay':
        cmd_replay(args.run_id)


if __name__ == '__main__':
    main()
